# syntax=docker/dockerfile:1

FROM golang:1.17-alpine

WORKDIR /app

COPY . ./
RUN go mod download

RUN go build .

ENV ENV=PRD
ENV VERSION=app/VERSION
ENV PORT=3000
ENV DB_DSN="host=board_db user=postgres password=postgres dbname=BOARD port=5432 sslmode=disable TimeZone=Asia/Shanghai"
ENV GIN_MODE=release

EXPOSE 3000

CMD [ "/app/server" ]